apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
    rules:
      - host: psychoschool.ru
        http:
          paths:
            - path: /?(.*)
              pathType: Prefix
              backend:
                service:
                  name: psycho-front
                  port:
                    number: 5000
