#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: letsencrypt-prod
#spec:
#  acme:
#    server: https://acme-v02.api.letsencrypt.org/directory
#    email: 'ollylut@gmail.com'
#    privateKeySecretRef:
#      name: letsencrypt-prod
#    solvers:
#      - http01:
#          ingress:
#            class: nginx
#      - dns01:
#          digitalocean:
#            tokenSecretRef:
#              name: digitalocean-dns
#              key: access-token
